import {
  calculateDocumentTotals,
  calculateInventoryValue,
  calculateLineTotal,
  calculatePendingBalance,
} from "@/lib/calculations/business";
import type {
  AccountPayable,
  CashSession,
  ChartPoint,
  Client,
  CompanySettings,
  DashboardMetric,
  DocumentItem,
  Employee,
  Expense,
  InventoryMovement,
  Invoice,
  Payment,
  Payroll,
  Product,
  Profile,
  Quote,
  Supplier,
  Warehouse,
} from "@/types/business";
import { formatCurrency } from "@/lib/utils";

const userId = "00000000-0000-4000-9000-000000000001";
const now = "2026-05-21T09:00:00.000Z";

export const profile: Profile = {
  id: "profile-1",
  user_id: userId,
  nombre: "Juliana Herrera",
  email: "julianaz101@hotmail.com",
  rol: "propietario",
  created_at: now,
  updated_at: now,
};

export const companySettings: CompanySettings = {
  id: "company-1",
  user_id: userId,
  nombre_empresa: "Nexo Admin Studio",
  identificacion: "NIT 901.555.231-4",
  email: "contacto@nexoadmin.local",
  telefono: "+57 300 555 0192",
  direccion: "Carrera 12 #45-30",
  ciudad: "Bogota",
  pais: "Colombia",
  moneda: "COP",
  impuesto_default: 19,
  prefijo_factura: "NI",
  consecutivo_factura: 1042,
  prefijo_cotizacion: "CT",
  consecutivo_cotizacion: 318,
  terminos_default:
    "Validez de 15 dias. Los precios pueden variar segun disponibilidad y alcance final aprobado.",
  color_marca: "#0f766e",
  created_at: now,
  updated_at: now,
};

export const clients: Client[] = [
  {
    id: "client-1",
    user_id: userId,
    nombre: "Andina Cafe SAS",
    tipo_documento: "NIT",
    numero_documento: "901245887",
    email: "compras@andinacafe.co",
    telefono: "6015550120",
    direccion: "Calle 80 #18-44",
    ciudad: "Bogota",
    departamento: "Cundinamarca",
    pais: "Colombia",
    notas: "Cliente recurrente con pagos a 30 dias.",
    estado: "activo",
    saldo_pendiente: 1870000,
    created_at: now,
    updated_at: now,
  },
  {
    id: "client-2",
    user_id: userId,
    nombre: "Merca Norte",
    tipo_documento: "NIT",
    numero_documento: "830912344",
    email: "contabilidad@mercanorte.com",
    telefono: "6045550144",
    direccion: "Avenida 7 #22-11",
    ciudad: "Medellin",
    departamento: "Antioquia",
    pais: "Colombia",
    notas: "Requiere orden de compra.",
    estado: "activo",
    saldo_pendiente: 910000,
    created_at: now,
    updated_at: now,
  },
  {
    id: "client-3",
    user_id: userId,
    nombre: "Clinica Serena",
    tipo_documento: "NIT",
    numero_documento: "900118220",
    email: "admin@clinicaserena.co",
    telefono: "6025550188",
    direccion: "Calle 5 #60-90",
    ciudad: "Cali",
    departamento: "Valle del Cauca",
    pais: "Colombia",
    notas: "Prefiere pagos por transferencia.",
    estado: "activo",
    saldo_pendiente: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "client-4",
    user_id: userId,
    nombre: "Taller Punto Azul",
    tipo_documento: "CC",
    numero_documento: "79888999",
    email: "taller@puntoazul.co",
    telefono: "6015550155",
    direccion: "Transversal 40 #12-18",
    ciudad: "Bogota",
    departamento: "Cundinamarca",
    pais: "Colombia",
    notas: "Cliente POS frecuente.",
    estado: "activo",
    saldo_pendiente: 320000,
    created_at: now,
    updated_at: now,
  },
  {
    id: "client-5",
    user_id: userId,
    nombre: "Hotel Horizonte",
    tipo_documento: "NIT",
    numero_documento: "890227310",
    email: "compras@hotelhorizonte.co",
    telefono: "6055550177",
    direccion: "Calle 2 #1-90",
    ciudad: "Cartagena",
    departamento: "Bolivar",
    pais: "Colombia",
    notas: "Solicita cotizaciones por proyecto.",
    estado: "inactivo",
    saldo_pendiente: 0,
    created_at: now,
    updated_at: now,
  },
];

export const suppliers: Supplier[] = [
  {
    id: "supplier-1",
    user_id: userId,
    nombre: "Distribuciones Prisma",
    tipo_documento: "NIT",
    numero_documento: "900777121",
    email: "ventas@prisma.co",
    telefono: "6015550200",
    direccion: "Zona Industrial 3",
    ciudad: "Bogota",
    notas: "Entrega cada martes.",
    estado: "activo",
    saldo_pendiente: 620000,
    created_at: now,
    updated_at: now,
  },
  {
    id: "supplier-2",
    user_id: userId,
    nombre: "Logistica Cima",
    tipo_documento: "NIT",
    numero_documento: "901113225",
    email: "facturas@cima.co",
    telefono: "6045550201",
    direccion: "Carrera 54 #30-20",
    ciudad: "Medellin",
    notas: "Servicio de transporte nacional.",
    estado: "activo",
    saldo_pendiente: 290000,
    created_at: now,
    updated_at: now,
  },
  {
    id: "supplier-3",
    user_id: userId,
    nombre: "TecnoInsumos",
    tipo_documento: "NIT",
    numero_documento: "830009554",
    email: "cartera@tecnoinsumos.co",
    telefono: "6015550202",
    direccion: "Calle 100 #19-70",
    ciudad: "Bogota",
    notas: "Garantias por serial.",
    estado: "activo",
    saldo_pendiente: 0,
    created_at: now,
    updated_at: now,
  },
  {
    id: "supplier-4",
    user_id: userId,
    nombre: "Servicios Nova",
    tipo_documento: "NIT",
    numero_documento: "900444555",
    email: "hola@serviciosnova.co",
    telefono: "6025550203",
    direccion: "Avenida 6N #20-10",
    ciudad: "Cali",
    notas: "Soporte mensual.",
    estado: "activo",
    saldo_pendiente: 180000,
    created_at: now,
    updated_at: now,
  },
  {
    id: "supplier-5",
    user_id: userId,
    nombre: "Papeleria Central",
    tipo_documento: "NIT",
    numero_documento: "800992100",
    email: "pedidos@papeleriacentral.co",
    telefono: "6015550204",
    direccion: "Calle 19 #8-40",
    ciudad: "Bogota",
    notas: "Compra menor mensual.",
    estado: "inactivo",
    saldo_pendiente: 0,
    created_at: now,
    updated_at: now,
  },
];

export const products: Product[] = [
  {
    id: "product-1",
    user_id: userId,
    nombre: "Kit cafe premium",
    descripcion: "Caja con mezclas seleccionadas y empaque corporativo.",
    tipo: "producto",
    sku: "CAF-KIT-01",
    codigo_barras: "770100000001",
    categoria: "Alimentos",
    precio_venta: 185000,
    costo: 112000,
    impuesto_porcentaje: 19,
    stock_actual: 24,
    stock_minimo: 10,
    unidad_medida: "unidad",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "product-2",
    user_id: userId,
    nombre: "Soporte mensual POS",
    descripcion: "Servicio de soporte, parametrizacion y mesa de ayuda.",
    tipo: "servicio",
    sku: "SRV-POS-01",
    codigo_barras: "",
    categoria: "Servicios",
    precio_venta: 420000,
    costo: 110000,
    impuesto_porcentaje: 19,
    stock_actual: 0,
    stock_minimo: 0,
    unidad_medida: "mes",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "product-3",
    user_id: userId,
    nombre: "Impresora termica NX-80",
    descripcion: "Impresora para recibos POS de 80mm.",
    tipo: "producto",
    sku: "POS-IMP-80",
    codigo_barras: "770100000003",
    categoria: "Hardware",
    precio_venta: 650000,
    costo: 480000,
    impuesto_porcentaje: 19,
    stock_actual: 4,
    stock_minimo: 5,
    unidad_medida: "unidad",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "product-4",
    user_id: userId,
    nombre: "Lector codigo barras",
    descripcion: "Lector USB para ventas rapidas.",
    tipo: "producto",
    sku: "POS-LECT-01",
    codigo_barras: "770100000004",
    categoria: "Hardware",
    precio_venta: 240000,
    costo: 155000,
    impuesto_porcentaje: 19,
    stock_actual: 8,
    stock_minimo: 4,
    unidad_medida: "unidad",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "product-5",
    user_id: userId,
    nombre: "Capacitacion administrativa",
    descripcion: "Sesion de entrenamiento para equipo operativo.",
    tipo: "servicio",
    sku: "SRV-CAP-02",
    codigo_barras: "",
    categoria: "Servicios",
    precio_venta: 350000,
    costo: 90000,
    impuesto_porcentaje: 0,
    stock_actual: 0,
    stock_minimo: 0,
    unidad_medida: "hora",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "product-6",
    user_id: userId,
    nombre: "Rollos termicos 80mm",
    descripcion: "Paquete por 10 unidades.",
    tipo: "producto",
    sku: "POS-ROL-80",
    codigo_barras: "770100000006",
    categoria: "Insumos",
    precio_venta: 78000,
    costo: 43000,
    impuesto_porcentaje: 19,
    stock_actual: 32,
    stock_minimo: 15,
    unidad_medida: "paquete",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "product-7",
    user_id: userId,
    nombre: "Tablet ventas 10 pulgadas",
    descripcion: "Equipo movil para toma de pedidos.",
    tipo: "producto",
    sku: "MOV-TAB-10",
    codigo_barras: "770100000007",
    categoria: "Hardware",
    precio_venta: 980000,
    costo: 760000,
    impuesto_porcentaje: 19,
    stock_actual: 3,
    stock_minimo: 3,
    unidad_medida: "unidad",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "product-8",
    user_id: userId,
    nombre: "Instalacion express",
    descripcion: "Implementacion inicial en sitio o remoto.",
    tipo: "servicio",
    sku: "SRV-IMP-01",
    codigo_barras: "",
    categoria: "Servicios",
    precio_venta: 590000,
    costo: 210000,
    impuesto_porcentaje: 19,
    stock_actual: 0,
    stock_minimo: 0,
    unidad_medida: "servicio",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "product-9",
    user_id: userId,
    nombre: "Base metalica caja",
    descripcion: "Caja registradora manual con bandeja.",
    tipo: "producto",
    sku: "POS-CAJ-01",
    codigo_barras: "770100000009",
    categoria: "Hardware",
    precio_venta: 310000,
    costo: 210000,
    impuesto_porcentaje: 19,
    stock_actual: 2,
    stock_minimo: 4,
    unidad_medida: "unidad",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "product-10",
    user_id: userId,
    nombre: "Plan consultoria financiera",
    descripcion: "Acompanamiento para estructurar reportes internos.",
    tipo: "servicio",
    sku: "SRV-FIN-01",
    codigo_barras: "",
    categoria: "Consultoria",
    precio_venta: 1250000,
    costo: 480000,
    impuesto_porcentaje: 19,
    stock_actual: 0,
    stock_minimo: 0,
    unidad_medida: "proyecto",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
];

export const warehouses: Warehouse[] = [
  {
    id: "warehouse-1",
    user_id: userId,
    nombre: "Bodega principal",
    direccion: "Carrera 12 #45-30",
    responsable: "Juliana Herrera",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "warehouse-2",
    user_id: userId,
    nombre: "Punto de venta norte",
    direccion: "Calle 140 #9-18",
    responsable: "Mateo Ruiz",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
];

const item = (
  id: string,
  product: Product,
  cantidad: number,
  descuento = 0,
): DocumentItem => ({
  id,
  product_id: product.id,
  descripcion: product.nombre,
  cantidad,
  precio_unitario: product.precio_venta,
  descuento,
  impuesto_porcentaje: product.impuesto_porcentaje,
  total_linea: calculateLineTotal({
    cantidad,
    precio_unitario: product.precio_venta,
    descuento,
    impuesto_porcentaje: product.impuesto_porcentaje,
  }),
});

const quoteItems1 = [item("quote-item-1", products[2], 1), item("quote-item-2", products[4], 3)];
const quoteItems2 = [item("quote-item-3", products[0], 8, 5), item("quote-item-4", products[1], 1)];
const quoteItems3 = [item("quote-item-5", products[9], 1), item("quote-item-6", products[7], 1)];

const quoteTotals1 = calculateDocumentTotals(quoteItems1);
const quoteTotals2 = calculateDocumentTotals(quoteItems2);
const quoteTotals3 = calculateDocumentTotals(quoteItems3);

export const quotes: Quote[] = [
  {
    id: "quote-1",
    user_id: userId,
    numero: "CT-0318",
    client_id: clients[0].id,
    client_name: clients[0].nombre,
    fecha: "2026-05-03",
    fecha_vencimiento: "2026-05-18",
    estado: "aceptada",
    ...quoteTotals1,
    notas: "Incluye instalacion remota y soporte inicial.",
    terminos_condiciones: companySettings.terminos_default,
    items: quoteItems1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "quote-2",
    user_id: userId,
    numero: "CT-0319",
    client_id: clients[4].id,
    client_name: clients[4].nombre,
    fecha: "2026-05-12",
    fecha_vencimiento: "2026-05-27",
    estado: "enviada",
    ...quoteTotals2,
    notas: "Entrega en dos despachos.",
    terminos_condiciones: companySettings.terminos_default,
    items: quoteItems2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "quote-3",
    user_id: userId,
    numero: "CT-0320",
    client_id: clients[2].id,
    client_name: clients[2].nombre,
    fecha: "2026-05-15",
    fecha_vencimiento: "2026-05-30",
    estado: "borrador",
    ...quoteTotals3,
    notas: "Pendiente validar alcance con operaciones.",
    terminos_condiciones: companySettings.terminos_default,
    items: quoteItems3,
    created_at: now,
    updated_at: now,
  },
];

const invoiceItems1 = [item("invoice-item-1", products[2], 1), item("invoice-item-2", products[7], 1)];
const invoiceItems2 = [item("invoice-item-3", products[0], 5), item("invoice-item-4", products[5], 2)];
const invoiceItems3 = [item("invoice-item-5", products[1], 1), item("invoice-item-6", products[4], 2)];
const invoiceItems4 = [item("invoice-item-7", products[3], 2), item("invoice-item-8", products[5], 5)];
const invoiceItems5 = [item("invoice-item-9", products[8], 1), item("invoice-item-10", products[6], 1)];

function invoiceTotal(items: DocumentItem[]) {
  return calculateDocumentTotals(items);
}

const invoiceTotals = [
  invoiceTotal(invoiceItems1),
  invoiceTotal(invoiceItems2),
  invoiceTotal(invoiceItems3),
  invoiceTotal(invoiceItems4),
  invoiceTotal(invoiceItems5),
];

export const invoices: Invoice[] = [
  {
    id: "invoice-1",
    user_id: userId,
    numero: "NI-1042",
    client_id: clients[0].id,
    client_name: clients[0].nombre,
    quote_id: quotes[0].id,
    fecha: "2026-05-05",
    fecha_vencimiento: "2026-06-04",
    estado: "parcialmente_pagada",
    metodo_pago: "transferencia",
    ...invoiceTotals[0],
    total_pagado: 700000,
    saldo_pendiente: calculatePendingBalance(invoiceTotals[0].total, 700000),
    notas:
      "Este documento es un comprobante interno. No reemplaza una factura electronica valida ante la DIAN.",
    items: invoiceItems1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "invoice-2",
    user_id: userId,
    numero: "NI-1043",
    client_id: clients[1].id,
    client_name: clients[1].nombre,
    fecha: "2026-05-08",
    fecha_vencimiento: "2026-05-23",
    estado: "enviada",
    metodo_pago: "credito",
    ...invoiceTotals[1],
    total_pagado: 0,
    saldo_pendiente: invoiceTotals[1].total,
    notas:
      "Este documento es un comprobante interno. No reemplaza una factura electronica valida ante la DIAN.",
    items: invoiceItems2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "invoice-3",
    user_id: userId,
    numero: "NI-1044",
    client_id: clients[2].id,
    client_name: clients[2].nombre,
    fecha: "2026-05-10",
    fecha_vencimiento: "2026-05-10",
    estado: "pagada",
    metodo_pago: "transferencia",
    ...invoiceTotals[2],
    total_pagado: invoiceTotals[2].total,
    saldo_pendiente: 0,
    notas:
      "Este documento es un comprobante interno. No reemplaza una factura electronica valida ante la DIAN.",
    items: invoiceItems3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "invoice-4",
    user_id: userId,
    numero: "NI-1045",
    client_id: clients[3].id,
    client_name: clients[3].nombre,
    fecha: "2026-04-18",
    fecha_vencimiento: "2026-05-03",
    estado: "vencida",
    metodo_pago: "credito",
    ...invoiceTotals[3],
    total_pagado: 180000,
    saldo_pendiente: calculatePendingBalance(invoiceTotals[3].total, 180000),
    notas:
      "Este documento es un comprobante interno. No reemplaza una factura electronica valida ante la DIAN.",
    items: invoiceItems4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "invoice-5",
    user_id: userId,
    numero: "NI-1046",
    client_id: clients[0].id,
    client_name: clients[0].nombre,
    fecha: "2026-04-28",
    fecha_vencimiento: "2026-05-28",
    estado: "borrador",
    metodo_pago: "tarjeta",
    ...invoiceTotals[4],
    total_pagado: 0,
    saldo_pendiente: invoiceTotals[4].total,
    notas:
      "Este documento es un comprobante interno. No reemplaza una factura electronica valida ante la DIAN.",
    items: invoiceItems5,
    created_at: now,
    updated_at: now,
  },
];

export const payments: Payment[] = [
  {
    id: "payment-1",
    user_id: userId,
    invoice_id: invoices[0].id,
    invoice_number: invoices[0].numero,
    client_name: invoices[0].client_name,
    fecha: "2026-05-06",
    valor: 700000,
    metodo_pago: "transferencia",
    referencia: "TR-8832",
    notas: "Primer abono confirmado.",
    created_at: now,
  },
  {
    id: "payment-2",
    user_id: userId,
    invoice_id: invoices[2].id,
    invoice_number: invoices[2].numero,
    client_name: invoices[2].client_name,
    fecha: "2026-05-10",
    valor: invoices[2].total,
    metodo_pago: "transferencia",
    referencia: "TR-8910",
    notas: "Pago total.",
    created_at: now,
  },
  {
    id: "payment-3",
    user_id: userId,
    invoice_id: invoices[3].id,
    invoice_number: invoices[3].numero,
    client_name: invoices[3].client_name,
    fecha: "2026-05-01",
    valor: 180000,
    metodo_pago: "efectivo",
    referencia: "RC-102",
    notas: "Abono en caja.",
    created_at: now,
  },
];

export const expenses: Expense[] = [
  {
    id: "expense-1",
    user_id: userId,
    supplier_id: suppliers[0].id,
    supplier_name: suppliers[0].nombre,
    categoria: "Inventario",
    descripcion: "Compra de insumos y kits base",
    fecha: "2026-05-02",
    valor: 1380000,
    impuesto: 262200,
    total: 1642200,
    metodo_pago: "transferencia",
    estado: "pagado",
    created_at: now,
    updated_at: now,
  },
  {
    id: "expense-2",
    user_id: userId,
    supplier_id: suppliers[1].id,
    supplier_name: suppliers[1].nombre,
    categoria: "Logistica",
    descripcion: "Despachos regionales",
    fecha: "2026-05-08",
    valor: 290000,
    impuesto: 0,
    total: 290000,
    metodo_pago: "credito",
    estado: "pendiente",
    created_at: now,
    updated_at: now,
  },
  {
    id: "expense-3",
    user_id: userId,
    supplier_id: suppliers[3].id,
    supplier_name: suppliers[3].nombre,
    categoria: "Software",
    descripcion: "Herramientas de productividad",
    fecha: "2026-05-11",
    valor: 180000,
    impuesto: 34200,
    total: 214200,
    metodo_pago: "tarjeta",
    estado: "pagado",
    created_at: now,
    updated_at: now,
  },
  {
    id: "expense-4",
    user_id: userId,
    categoria: "Servicios",
    descripcion: "Internet oficina",
    fecha: "2026-05-15",
    valor: 145000,
    impuesto: 0,
    total: 145000,
    metodo_pago: "transferencia",
    estado: "pagado",
    created_at: now,
    updated_at: now,
  },
  {
    id: "expense-5",
    user_id: userId,
    supplier_id: suppliers[2].id,
    supplier_name: suppliers[2].nombre,
    categoria: "Hardware",
    descripcion: "Repuestos y accesorios",
    fecha: "2026-04-30",
    valor: 620000,
    impuesto: 117800,
    total: 737800,
    metodo_pago: "credito",
    estado: "vencido",
    created_at: now,
    updated_at: now,
  },
];

export const accountsPayable: AccountPayable[] = [
  {
    id: "ap-1",
    user_id: userId,
    supplier_id: suppliers[0].id,
    supplier_name: suppliers[0].nombre,
    descripcion: "Saldo compra inventario",
    fecha_vencimiento: "2026-05-25",
    total: 620000,
    saldo_pendiente: 620000,
    estado: "pendiente",
    created_at: now,
    updated_at: now,
  },
  {
    id: "ap-2",
    user_id: userId,
    supplier_id: suppliers[1].id,
    supplier_name: suppliers[1].nombre,
    descripcion: "Servicios logisticos",
    fecha_vencimiento: "2026-05-30",
    total: 290000,
    saldo_pendiente: 290000,
    estado: "pendiente",
    created_at: now,
    updated_at: now,
  },
  {
    id: "ap-3",
    user_id: userId,
    supplier_id: suppliers[3].id,
    supplier_name: suppliers[3].nombre,
    descripcion: "Soporte tecnico mensual",
    fecha_vencimiento: "2026-05-12",
    total: 180000,
    saldo_pendiente: 180000,
    estado: "vencido",
    created_at: now,
    updated_at: now,
  },
];

export const inventoryMovements: InventoryMovement[] = [
  {
    id: "movement-1",
    user_id: userId,
    product_id: products[0].id,
    product_name: products[0].nombre,
    warehouse_id: warehouses[0].id,
    warehouse_name: warehouses[0].nombre,
    tipo_movimiento: "entrada",
    cantidad: 30,
    costo_unitario: products[0].costo,
    motivo: "Compra inicial",
    referencia_tipo: "gasto",
    referencia_id: expenses[0].id,
    fecha: "2026-05-02",
    created_at: now,
  },
  {
    id: "movement-2",
    user_id: userId,
    product_id: products[0].id,
    product_name: products[0].nombre,
    warehouse_id: warehouses[1].id,
    warehouse_name: warehouses[1].nombre,
    tipo_movimiento: "traslado",
    cantidad: 6,
    costo_unitario: products[0].costo,
    motivo: "Reposicion punto norte",
    fecha: "2026-05-04",
    created_at: now,
  },
  {
    id: "movement-3",
    user_id: userId,
    product_id: products[2].id,
    product_name: products[2].nombre,
    warehouse_id: warehouses[0].id,
    warehouse_name: warehouses[0].nombre,
    tipo_movimiento: "salida",
    cantidad: 1,
    costo_unitario: products[2].costo,
    motivo: "Factura NI-1042",
    referencia_tipo: "factura",
    referencia_id: invoices[0].id,
    fecha: "2026-05-05",
    created_at: now,
  },
  {
    id: "movement-4",
    user_id: userId,
    product_id: products[3].id,
    product_name: products[3].nombre,
    warehouse_id: warehouses[0].id,
    warehouse_name: warehouses[0].nombre,
    tipo_movimiento: "salida",
    cantidad: 2,
    costo_unitario: products[3].costo,
    motivo: "Factura NI-1045",
    referencia_tipo: "factura",
    referencia_id: invoices[3].id,
    fecha: "2026-04-18",
    created_at: now,
  },
  {
    id: "movement-5",
    user_id: userId,
    product_id: products[5].id,
    product_name: products[5].nombre,
    warehouse_id: warehouses[1].id,
    warehouse_name: warehouses[1].nombre,
    tipo_movimiento: "salida",
    cantidad: 5,
    costo_unitario: products[5].costo,
    motivo: "Venta POS",
    fecha: "2026-05-12",
    created_at: now,
  },
  {
    id: "movement-6",
    user_id: userId,
    product_id: products[6].id,
    product_name: products[6].nombre,
    warehouse_id: warehouses[0].id,
    warehouse_name: warehouses[0].nombre,
    tipo_movimiento: "ajuste",
    cantidad: -1,
    costo_unitario: products[6].costo,
    motivo: "Equipo de demostracion",
    fecha: "2026-05-14",
    created_at: now,
  },
  {
    id: "movement-7",
    user_id: userId,
    product_id: products[8].id,
    product_name: products[8].nombre,
    warehouse_id: warehouses[0].id,
    warehouse_name: warehouses[0].nombre,
    tipo_movimiento: "entrada",
    cantidad: 3,
    costo_unitario: products[8].costo,
    motivo: "Compra proveedor",
    fecha: "2026-04-30",
    created_at: now,
  },
  {
    id: "movement-8",
    user_id: userId,
    product_id: products[8].id,
    product_name: products[8].nombre,
    warehouse_id: warehouses[1].id,
    warehouse_name: warehouses[1].nombre,
    tipo_movimiento: "traslado",
    cantidad: 1,
    costo_unitario: products[8].costo,
    motivo: "Exhibicion POS",
    fecha: "2026-05-02",
    created_at: now,
  },
  {
    id: "movement-9",
    user_id: userId,
    product_id: products[2].id,
    product_name: products[2].nombre,
    warehouse_id: warehouses[0].id,
    warehouse_name: warehouses[0].nombre,
    tipo_movimiento: "entrada",
    cantidad: 5,
    costo_unitario: products[2].costo,
    motivo: "Compra hardware",
    fecha: "2026-04-26",
    created_at: now,
  },
  {
    id: "movement-10",
    user_id: userId,
    product_id: products[5].id,
    product_name: products[5].nombre,
    warehouse_id: warehouses[0].id,
    warehouse_name: warehouses[0].nombre,
    tipo_movimiento: "entrada",
    cantidad: 40,
    costo_unitario: products[5].costo,
    motivo: "Reposicion insumos",
    fecha: "2026-05-01",
    created_at: now,
  },
];

export const cashSessions: CashSession[] = [
  {
    id: "cash-1",
    user_id: userId,
    apertura: "2026-05-21T08:00:00.000Z",
    base_inicial: 200000,
    efectivo: 480000,
    transferencia: 920000,
    tarjeta: 610000,
    total_sistema: 2210000,
    total_contado: 2205000,
    diferencia: -5000,
    observaciones: "Diferencia menor pendiente de conciliacion.",
    estado: "abierta",
    created_at: now,
    updated_at: now,
  },
];

export const employees: Employee[] = [
  {
    id: "employee-1",
    user_id: userId,
    nombre: "Mateo Ruiz",
    documento: "1020304050",
    email: "mateo@nexoadmin.local",
    telefono: "3005551100",
    cargo: "Asesor comercial",
    salario_base: 2200000,
    tipo_contrato: "Termino indefinido",
    fecha_ingreso: "2025-10-01",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "employee-2",
    user_id: userId,
    nombre: "Laura Pineda",
    documento: "1030405060",
    email: "laura@nexoadmin.local",
    telefono: "3005551101",
    cargo: "Auxiliar administrativa",
    salario_base: 1850000,
    tipo_contrato: "Termino fijo",
    fecha_ingreso: "2026-01-15",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
  {
    id: "employee-3",
    user_id: userId,
    nombre: "Camilo Torres",
    documento: "1040506070",
    email: "camilo@nexoadmin.local",
    telefono: "3005551102",
    cargo: "Tecnico soporte",
    salario_base: 2400000,
    tipo_contrato: "Prestacion de servicios",
    fecha_ingreso: "2026-02-01",
    estado: "activo",
    created_at: now,
    updated_at: now,
  },
];

export const payrolls: Payroll[] = [
  {
    id: "payroll-1",
    user_id: userId,
    periodo: "2026-05",
    empleado_id: employees[0].id,
    employee_name: employees[0].nombre,
    salario_base: employees[0].salario_base,
    dias_trabajados: 30,
    horas_extra: 120000,
    deducciones: 176000,
    bonificaciones: 80000,
    total_pagado: 2224000,
    estado: "pagada",
    created_at: now,
    updated_at: now,
  },
  {
    id: "payroll-2",
    user_id: userId,
    periodo: "2026-05",
    empleado_id: employees[1].id,
    employee_name: employees[1].nombre,
    salario_base: employees[1].salario_base,
    dias_trabajados: 30,
    horas_extra: 0,
    deducciones: 148000,
    bonificaciones: 120000,
    total_pagado: 1822000,
    estado: "pagada",
    created_at: now,
    updated_at: now,
  },
  {
    id: "payroll-3",
    user_id: userId,
    periodo: "2026-05",
    empleado_id: employees[2].id,
    employee_name: employees[2].nombre,
    salario_base: employees[2].salario_base,
    dias_trabajados: 20,
    horas_extra: 0,
    deducciones: 0,
    bonificaciones: 0,
    total_pagado: 1600000,
    estado: "borrador",
    created_at: now,
    updated_at: now,
  },
];

const monthRevenue = invoices
  .filter((invoice) => invoice.fecha.startsWith("2026-05"))
  .reduce((sum, invoice) => sum + invoice.total, 0);
const monthExpenses = expenses
  .filter((expense) => expense.fecha.startsWith("2026-05"))
  .reduce((sum, expense) => sum + expense.total, 0);
const pendingInvoices = invoices.filter((invoice) =>
  ["enviada", "parcialmente_pagada", "vencida"].includes(invoice.estado),
);
const pendingQuotes = quotes.filter((quote) =>
  ["borrador", "enviada"].includes(quote.estado),
);
const lowStockProducts = products.filter(
  (product) => product.tipo === "producto" && product.stock_actual <= product.stock_minimo,
);
const accountsReceivable = invoices.reduce((sum, invoice) => sum + invoice.saldo_pendiente, 0);

export const dashboardMetrics: DashboardMetric[] = [
  {
    label: "Ventas del mes",
    value: formatCurrency(monthRevenue),
    helper: "Facturas internas emitidas en mayo",
    trend: "+18%",
  },
  {
    label: "Gastos del mes",
    value: formatCurrency(monthExpenses),
    helper: "Compras, servicios e insumos",
    trend: "-6%",
  },
  {
    label: "Utilidad estimada",
    value: formatCurrency(monthRevenue - monthExpenses),
    helper: "Antes de impuestos y ajustes contables",
    trend: "+11%",
  },
  {
    label: "Cuentas por cobrar",
    value: formatCurrency(accountsReceivable),
    helper: `${pendingInvoices.length} documentos pendientes`,
    trend: "3 alertas",
  },
];

export const salesChart: ChartPoint[] = [
  { name: "Ene", ventas: 11800000, gastos: 5200000, utilidad: 6600000 },
  { name: "Feb", ventas: 14200000, gastos: 6400000, utilidad: 7800000 },
  { name: "Mar", ventas: 13600000, gastos: 5800000, utilidad: 7800000 },
  { name: "Abr", ventas: 15100000, gastos: 7100000, utilidad: 8000000 },
  { name: "May", ventas: monthRevenue, gastos: monthExpenses, utilidad: monthRevenue - monthExpenses },
  { name: "Jun", ventas: 9700000, gastos: 4300000, utilidad: 5400000 },
];

export const expenseCategoryChart: ChartPoint[] = [
  { name: "Inventario", total: 1642200 },
  { name: "Logistica", total: 290000 },
  { name: "Software", total: 214200 },
  { name: "Servicios", total: 145000 },
  { name: "Hardware", total: 737800 },
];

export const dashboardSummary = {
  pendingInvoices,
  pendingQuotes,
  lowStockProducts,
  activeClients: clients.filter((client) => client.estado === "activo").length,
  inventoryValue: calculateInventoryValue(products),
  alerts: [
    "3 productos requieren reposicion o ajuste de minimo.",
    "1 factura interna vencida requiere gestion de cartera.",
    "1 cuenta por pagar esta vencida.",
    "Supabase Auth y RLS estan preparados para conectar credenciales reales.",
  ],
};
